-- Portfolio D1 Seed Data
-- 从 JSON 文件导入的数据

-- 插入项目数据
INSERT INTO projects (id, title, description, overview, technologies, duration, team_size, role, status, live_url, github_url, display_order) VALUES
('ai-native-trpg-platform', 'AI Native TRPG Platform', 'An AI-native TRPG platform that provides AI-driven TRPG gaming experiences.', 'This AI Native TRPG Platform represents a cutting-edge TRPG experience where creators can easily build, customize, and share their own TRPG games with deep AI technology integration.', '["Next.js","TypeScript","Tailwind CSS","AI Integration"]', 'September 2025 - Present', '1 developer', 'Full-stack Developer', 'prototype', NULL, NULL, 0),
('rust-python-microservices', 'Rust/Python Microservices API', 'High-performance microservices architecture built with Rust Axum and Python FastAPI.', 'This microservices cluster integrates Rust''s high-performance advantages with Python''s flexibility, providing complete solutions for user authentication, authorization, and resource management.', '["Rust","tokio/Axum","Python","FastAPI","PostgreSQL","Redis","Docker"]', 'May 2025 - Present', '1 developer', 'Full-stack Developer', 'in progress', NULL, 'https://github.com/Preference-cmd/inceptae', 1),
('ros2-autonomous-vehicle', 'ROS2-based Intelligent Autonomous Vehicle', 'A comprehensive autonomous vehicle system built on ROS2 framework.', 'This intelligent autonomous vehicle system represents a complete implementation of self-driving technology using the ROS2 framework with advanced perception, decision-making, and execution modules.', '["ROS2","VINS-Fusion","Octomap","Navigation2","C++","Python"]', 'February 2023 - June 2023', '1 developer', 'System Designer & Developer', 'completed', NULL, 'https://github.com/username/ros2-autonomous-vehicle', 2),
('3d-reconstruction-app', 'Product Preview 3D Reconstruction', 'An automated 3D model generation application from product images.', 'This innovative application automates the process of generating 3D models from product images or videos, providing e-commerce businesses with enhanced product visualization capabilities.', '["Python","Meta SAM2","Colmap","OpenMVS","OpenCV"]', 'May 2025', '1 developer', 'Solo Developer', 'prototype', 'https://3d-reconstruction-demo.vercel.app', NULL, 3),
('computer-vision-tracking', 'Computer Vision Target Tracking System', 'Real-time target tracking system with YOLOv5 and PID control.', 'This computer vision target tracking system was developed as part of RoboCon competition research, focusing on real-time target detection and tracking in complex environments.', '["Python","OpenCV","YOLOv5","PID Control","Computer Vision"]', 'July 2021 - March 2022', '1 developer', 'Computer Vision Engineer', 'completed', NULL, NULL, 4),
('inverted-pendulum-control', 'LQR Control System for Inverted Pendulum', 'Control system design using Luenberger observer and LQR algorithms.', 'This project focuses on designing and implementing an advanced control system for a single inverted pendulum using Luenberger observer for state estimation and Linear Quadratic Regulator (LQR) for optimal control.', '["MATLAB/Simulink","Control Theory","LQR Controller","Luenberger Observer"]', 'October 2022 - November 2022', '1 developer', 'Control System Designer', 'completed', NULL, NULL, 5);

-- 插入英文简历数据
INSERT INTO resume_data (locale, personal_info, contact, skills, tools, languages, work_experience, key_projects, education) VALUES
('en',
  '{"name":"SHAN LIN","title":"AI/Web Developer","subtitle":"Full-Stack Developer & AI Enthusiast"}',
  '{"website":"pref2rence.inceptae.com","email":"noreply@example.com","phone":"+86 REDACTED","location":"REDACTED","github":"github.com/Preference-cmd"}',
  '["AI/ML Integration","Data Analysis","System Architecture","Computer Vision","RPA"]',
  '["Rust","Python","TypeScript","Docker","CI/CD"]',
  '["Chinese (Native)","English (CET6)"]',
  '[{"company":"GuangDong Yesheen Technology Co., Ltd.","position":"AI/Full-Stack Developer, Project lead of robot project","period":"NOV 2025 - FEB 2026","responsibilities":["Developed the complete face-recognition application for edge computing device using Tauri2","Collecting and processing data with Dify workflows for model training","Design and implement architecture of the AI system for object detection, pose estimation and tracking using Dora-rs and ROS2 with Docker"]},{"company":"Chongqing Jiangjin District Meitu Agricultural Professional Cooperative","position":"Huarun Sanjiu Wild Chrysanthemum Project, Management & Information Analysis Engineer","period":"SEP 2024 - APR 2025","responsibilities":["Managed workflows using RPA tools like YingDao and Feishu, optimizing warehouse, personnel, and production management processes","Collected crop growth-related data using object detection methods and processed data using Numpy, Pandas and other tools"]},{"company":"Guilin Yingzhi Intelligent Technology Co., Ltd.","position":"Robot R&D Assistant Engineer","period":"DEC 2022 - APR 2023","responsibilities":["Developed image processing modules using OpenCV and ROS: image filtering, enhancement, semantic segmentation, etc.","Completed visual sensor calibration using Kalibr toolkit and conducted algorithm testing"]}]',
  '[{"name":"Rust Axum/Python FastAPI Microservice Backend","period":"MAY 2025 - PRESENT","description":["High-performance microservice backend with Rust Axum + PostgreSQL + Redis, building authentication, authorization and other basic services","Integrated Python FastAPI with LangGraph to build large language model backend services"]},{"name":"Product Preview Visual 3D Reconstruction Application","period":"MAY 2025 - MAY 2025","description":["Developed automatic object annotation and image mask generation module based on Meta SAM2","Python automated Colmap-OpenMVS to build dense reconstruction pipeline, achieving reconstruction from images/videos to high-fidelity 3D models"]},{"name":"ROS2 Autonomous Exploration Unmanned Vehicle","period":"FEB 2023 - JUN 2023","description":["Completed communication and distributed computing between edge platform and PC platform based on ROS2 system","Used VINS-Fusion and Octomap to complete robot visual localization and mapping","Used Navigation2 to complete robot navigation functionality"]},{"name":"Machine Vision-based Target Tracking System","period":"JUL 2021 - MAR 2022","description":["Implemented target detection functionality using OpenCV and YOLOv5","Built feedback control algorithms using target detection to drive motors for continuous camera tracking of targets"]}]',
  '[{"institution":"Guilin University of Aerospace Technology","degree":"BSc Robotics&Automation","period":"SEP 2019 - JUN 2023","description":[]}]'
);

-- 插入中文简历数据
INSERT INTO resume_data (locale, personal_info, contact, skills, tools, languages, work_experience, key_projects, education) VALUES
('zh',
  '{"name":"单林","title":"AI/Web 开发者","subtitle":"全栈开发者 & AI 爱好者"}',
  '{"website":"pref2rence.inceptae.com","email":"noreply@example.com","phone":"+86 REDACTED","location":"REDACTED","github":"github.com/Preference-cmd"}',
  '["AI/ML 集成","数据分析","系统架构","计算机视觉","RPA"]',
  '["Rust","Python","TypeScript","Docker","CI/CD"]',
  '["中文（母语）","英语（CET6）"]',
  '[{"company":"重庆市江津区美图农业专业合作社","position":"华润三九野菊花项目，信息分析工程师","period":"2024年9月 - 2025年4月","responsibilities":["使用RPA工具（钉钉、飞书）管理工作流程，优化仓库、人员、生产管理流程","使用目标检测方法收集作物生长相关数据，使用Numpy、Pandas等工具处理数据"]},{"company":"桂林英智智能科技有限公司","position":"机器人研发助理工程师","period":"2022年12月 - 2023年4月","responsibilities":["使用OpenCV和ROS开发图像处理模块：图像滤波、增强、语义分割等","使用Kalibr工具完成视觉传感器标定并进行算法测试"]}]',
  '[{"name":"Rust Axum/Python FastAPI 微服务后端","period":"2025年5月 - 至今","description":["使用 Rust Axum + PostgreSQL + Redis 构建高性能微服务后端，实现认证、授权等基础服务","集成 Python FastAPI 与 LangGraph 构建大语言模型后端服务"]},{"name":"商品预览3D重建应用","period":"2025年5月","description":["基于 Meta SAM2 开发自动对象标注和图像遮罩生成模块","Python 自动化 Colmap-OpenMVS 构建密集重建流水线，实现从图像/视频到高保真 3D 模型的重建"]},{"name":"ROS2 自主探索无人车","period":"2023年2月 - 2023年6月","description":["基于 ROS2 系统完成边缘平台与 PC 平台的通信和分布式计算","使用 VINS-Fusion 和 Octomap 完成机器人视觉定位和建图","使用 Navigation2 完成机器人导航功能"]},{"name":"机器视觉目标跟踪系统","period":"2021年7月 - 2022年3月","description":["使用 OpenCV 和 YOLOv5 实现目标检测功能","构建基于目标检测的反馈控制算法，驱动电机实现相机对目标的持续跟踪"]}]',
  '[{"institution":"桂林航天工业学院","degree":"学士学位 机器人工程","period":"2019年9月 - 2023年6月","description":[]}]'
);
